swagger: '2.0'

info:
  description: the server API of the Homeworks
  version: 1.0.0
  title: server API
    
host: 47.102.120.167:2333
basePath: /api
tags:
  - name: assignment
    description: assignment
  - name: course
    description: course
  - name: user
    description: user
    
schemes:
  - https
  - http
  
paths:
  /login/:
    post:
      tags:
        - user
      summary: login
      description: login for account
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: data
          in: body
          description: post data
          schema:
            required:
              - userName
              - password
            properties:
              userName:
                type: string
                description: 账号（学号）
              password:
                type: string
                description: 云课堂密码
      responses:
        200:
          description: successfully login
          schema:
            type: object
            required:
              - cookie
              - token
            properties:
              cookie: 
                type: string
              token:
                type: string
              msg:
                type: string
                description: 登录结果信息
              userName:
                type: string
                description: 用户学号
              realName:
                type: string
                description: 用户姓名
        400:
          description: 参数不全
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 用户名或密码错误
          schema:
            type: object
            properties:
              msg:
                type: string
   #   security:
    #    - petstore_auth:
     #       - 'write:pets'
      #      - 'read:pets'
      
  /course/list/:
    get:
      tags:
        - course
      summary: 课堂列表
      description: Get course list
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: cookie
          in: header
          description: cookie
          required: true
          type: string
        - name: token
          in: header
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              msg:
                type: string
              cookie:
                type: string
              total:
                type: integer
                description: 课堂总数
              courseList:
                type: array
                items:
                  properties:
                    courseName:
                      type: string
                    teacher:
                      type: string
                    siteId:
                      type: string
                      description: 课堂站点ID
        400:
          description: 参数不全
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string
            
   #   security:
    #    - petstore_auth:
     #       - 'write:pets'
      #      - 'read:pets'
      
  /course/{siteId}/assignment/list/:
    get:
      tags:
        - course
      summary: 获取某一课堂任务列表
      description: get assignments of a class
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: cookie
          in: header
          description: cookie
          required: true
          type: string
        - name: token
          in: header
          required: true
          type: string
        - name: siteId
          in: path
          description: ID of courses
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              cookie:
                type: string
              msg:
                type: string
              siteId:
                type: string
              total:
                type: integer
              data:
                type: array
                items:
                  properties:
                    status:
                      type: integer
                      description: 未提交：0，待批阅：1，已驳回：2，已批阅：3
                    assignName:
                      type: string
                      description: 任务/作业名称
                    beginTime:
                      type: integer
                      description: 开始时间
                    endTime:
                      type: integer
                      description: 结束时间
                    assignId:
                      type: string
                      description: 任务ID
        400:
          description: 参数不全
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string
        404:
          description: not found
          schema:
            type: object
            properties:
              msg:
                type: string
                
      deprecated: false
      #该路由是否不推荐使用/不可用
      
  /assignment/{siteId}/{assignId}/info/:
    get:
      tags:
        - assignment
      summary: 任务详情
      description: specific information of assignments
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: cookie
          in: header
          description: cookie
          required: true
          type: string
        - name: token
          in: header
          required: true
          type: string
        - name: siteId
          in: path
          required: true
          type: string
        - name: assignId
          in: path
          required: true
          type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              cookie:
                type: string
              msg:
                type: string
              siteId:
                type: string
              assignId:
                type: string
              courseName:
                type: string
                description: 课堂名
              assignName:
                type: string
                description: 任务名
              status:
                type: integer
                description: 未提交：0，待批阅：1，已驳回：2，已批阅：3
              beginTime:
                type: integer
              endTime:
                type: integer
              content:
                type: string
                description: 作业要求，颁布的作业
              pointNum:
                type: integer
                description: 已批阅数
              isGroup:
                type: integer
                description: 分组作业：1，个人作业：0
              groupNum:
                type: integer
                description: 小组数
              studentNum:
                type: integer
                description: 学生数
              groupPoint:
                type: integer
                description: 小组得分
              personalPoint:
                type: integer
                description: 个人得分
              feedback:
                type: string
                description: 反馈
              assignAttachmentNum:
                type: integer
                description: 作业提供的附件的数目
              assignAttachment:
                description: 作业提供的附件的信息
                type: array
                items:
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                      description: 附件名称
                    ext:
                      type: string
                      description: 附件格式
              submitAttachmentNum:
                type: integer
                description: 以作业形式提交的附件的数目
              submitAttachment:
                description: 以作业形式提交的附件的信息
                type: array
                items:
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                      description: 附件名
                    ext:
                      type: string
                      description: 附件格式
                    uploadTime:
                      type: integer
                      description: 附件上传时间
              submitContent:
                type: string
                description: 作业内容，提交的作业
        400:
          description: 参数不全
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string
        404:
          description: not found
          schema:
            type: object
            properties:
              msg:
                type: string
      #security:
       # - petstore_auth:
        #    - 'write:pets'
         #   - 'read:pets'
  
  /assignment/list/:
    get:
      tags:
        - assignment
      summary: assignment list
      description: get the assignment list
      #operationId: uploadFile
      produces:
        - application/json
      parameters:
        - name: cookie
          in: header
          description: cookie
          required: true
          type: string
        - name: token
          in: header
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              cookie:
                type: string
              msg:
                type: string
              total:
                type: integer
              assignList:
                type: array
                items:
                  properties:
                    siteId:
                      type: string
                    status:
                      type: integer
                    courseName:
                      type: string
                    assignName:
                      type: string
                    teacher:
                      type: string
                    beginTime:
                      type: integer
                    endTime:
                      type: integer
                    assignId:
                      type: string
        400:
          description: 参数不全
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string

  /userInfo/:
    get:
      tags:
        - user
      summary: user information
      description: user information
      #operationId: placeOrder
      produces:
        - application/json
      parameters:
        - name: cookie
          in: header
          required: true
          type: string
        - name: token
          in: header
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              cookie:
                type: string
              msg:
                type: string
              realName:
                type: string
              userName:
                type: string
              apartment:
                type: string
              email:
                type: string
                
  /notice/:
    get:
      tags:
        - assignment
      summary: 未提交任务提醒
      description: notice the unsubmit assignments
      parameters:
        - name: cookie
          in: header
          required: true
          type: string
        - name: token
          in: header
          required: true
          type: string
      responses:
        200:
          description: success
          schema:
            properties:
              cookie:
                type: string
              msg:
                type: string
              userName:
                type: string
              realName:
                type: string
              total:
                type: integer
                description: 未提交总数
              data:
                type: array
                items:
                  properties:
                    courseName:
                      type: string
                    assignName:
                      type: string
                    teacher:
                      type: string
                    siteId:
                      type: string
                    assignId:
                      type: string
                    beginTime:
                      type: integer
                    endTime:
                      type: integer
        400:
          description: 参数不全
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string
                      
  /search/:
    get:
      tags:
        - assignment
      summary: 搜索
      description: search an assignment
      parameters:
        - name: cookie
          in: header
          required: true
          type: string
        - name: keyword
          in: query
          description: 搜索关键词
          type: string
        - name: token
          in: header
          required: true
          type: string
      responses:
        200:
          description: successful operation
          schema:
            type: object
            properties:
              cookie:
                type: string
              msg:
                type: string
              total:
                type: integer
              data:
                type: array
                items:
                  properties:
                    assignId:
                      type: string
                    siteId:
                      type: string
                    assignName:
                      type: string
                    courseName:
                      type: string
                    status:
                      type: integer
                    beginTime:
                      type: integer
                    endTime:
                      type: integer
                    teacher:
                      type: string
        400:
          description: 参数不全
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string
        404:
          description: Not found
          schema:
            type: object
            properties:
              msg:
                type: string
            
  /mail/:
    post:
      tags:
        - user
      summary: 添加邮箱
      parameters:
        - name: cookie
          in: header
          required: true
          type: string
        - name: token
          in: header
          required: true
          type: string
        - name: data
          in: body
          schema:
            required:
              - email
            properties:
              email:
                type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              msg:
                type: string
              cookie:
                type: string
        400:
          description: 参数不全
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string
    put:
      tags:
        - user
      summary: 修改邮箱
      parameters:
        - name: cookie
          in: header
          required: true
          type: string
        - name: token
          in: header
          required: true
          type: string
        - name: data
          in: body
          schema:
            required:
              - email
            properties:
              email:
                type: string
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              msg:
                type: string
              cookie:
                type: string
        400:
          description: 参数不全
          schema:
            type: object
            properties:
              msg:
                type: string
        401:
          description: 身份认证错误
          schema:
            type: object
            properties:
              msg:
                type: string
